apps/lekker_class/config/routes.rb
Rails.application.routes.draw do

  resources :places do
    member do
      post 'upvote'
    end
  end

  root 'places#index'

end

apps/lekker_class/app/models/place.rb
class Place < ActiveRecord::Base
	validates :name, presence: true
end

apps/lekker_class/app/controllers/places_controller.rb
class PlacesController < ActionController::Base
	def index
		@places = Place.all.order(:vote).reverse_order
	end
	def destroy
    	@place = Place.find(params[:id])
    	@place.destroy
 
    	redirect_to places_path
   	end
	def show
		@place = Place.find params[:id]
	end
	def new
		@place = Place.new
	end
	def create
		@place = Place.new(place_params)

		if @place.save
			redirect_to @place
		else
			render :new
		end
	end
	def update
	@place = Place.find(params[:id])
 
    if @place.update(place_params)
      redirect_to @place
    else
      render 'edit'
    end
	end
	def edit
    	@place =Place.find(params[:id])
  	end
  	def upvote
  		@place = Place.find(params[:id])
  		@place.increment!(:vote, by = 1)
  		redirect_to(places_path)
	end
	
	private
   	def place_params
		params.require(:place).permit(:name, :description, :address, :image)
	end
end

apps/lekker_class/app/views/places/edit.html.erb
<h1>Edit place</h1>
 

 
<%= form_for :place, url: place_path(@place), method: :patch do |f| %>
 
  <% if @place.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@place.errors.count, "error") %> prohibited
        this place from being saved:
      </h2>
      <ul>
        <% @place.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
    <p>
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </p>
  <p>
    <%= f.label :image %><br>
    <%= f.text_area :image %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', places_path %>

apps/lekker_class/app/views/places/form.html.erb
<%= form_for @place do |f| %>
 
  <% if @place.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@place.errors.count, "error") %> prohibited
        this place from being saved:
      </h2>
      <ul>
        <% @place.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
   <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
    <p>
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </p>
  <p>
    <%= f.label :image %><br>
    <%= f.text_area :image %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

apps/lekker_class/app/views/places/index.html.erb
<div align='center'><h1>Here are all the coolest places in Cape Town:</h1><br>
<%= link_to 'Add a New Place', new_place_path %></div>
<%@places.each do |place|%>
	<strong><div align='center'>
	<h2><%= link_to place.name, place_path(place.id) %></strong></h2>
	<p><%=place.description%></p>
	<p><%=place.address%></p>
	<p><%= pluralize(place.vote, "vote") %></p>
    <p><%= button_to '+1', upvote_place_path(place), method: :post %></p>
	<%= button_to 'Edit', edit_place_path(place), :method => :get %>
	

	<%= button_to "Delete", place, :method => :delete, data: {confirm: "Are you sure bru?"} %>
            

	
  </div><%end%>

apps/lekker_class/app/views/places/new.html.erb
<h1>New Place!</h1>

<%= form_for @place do |f| %>
	 <p>
		<%= f.label :name %><br>
		<%= f.text_field :name %>
	</p>

	<p>
		<%= f.label :description %><br>
		<%= f.text_area :description %>
	</p>
	<p>
		<%= f.label :address %><br>
		<%= f.text_area :address %>
	</p>
	<p>
		<%= f.label :image %><br>
		<%= f.text_area :image %>
	</p>
	 <p>
		<%= f.submit %>
	</p>

<% end %>

apps/lekker_class/app/views/places/show.html.erb
<h1><%=@place.name%></h1>

<p><%=@place.description%></p>

<p><%=@place.address%></p>


<img src=<%=@place.image%> height='250'><br>



<%= link_to 'Back to Index', places_path %>