apps/brugram/config/routes.rb
Rails.application.routes.draw do
  resources :photos
  resources :hashtags
  root 'photos#index'

end

apps/brugram/app/models/hashtag.rb
class Hashtag < ActiveRecord::Base
	has_and_belongs_to_many :photos
end

apps/brugram/app/models/photo.rb
class Photo < ActiveRecord::Base
	has_attached_file :image, :styles => { :medium => "500x500>", :thumb => "750x750>" }, :default_url => "/images/:style/missing.png"
  	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  	has_and_belongs_to_many :hashtags
end

apps/brugram/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

apps/brugram/app/controllers/hashtags_controller.rb
class HashtagsController < ApplicationController
	def show
		@hashtag=Hashtag.find(params[:id])
	end

	def index
		@hashtags = Hashtag.all
	end

end

apps/brugram/app/controllers/photos_controller.rb
class PhotosController < ApplicationController
	def new
  		@photo = Photo.new
  		@photo.save

	end
	def update
		@photo = Photo.find(params[:id])
 
	    if @photo.update(photo_params)

			array = @photo.caption.split(' ')
			array.each do |word|
				if word.include?("#")
					@hashtag = Hashtag.where(text: word).first_or_create(text: word)
				
					@photo.hashtags << @hashtag
					@photo.save
				end
			end
	      redirect_to @photo
	    else
	      render 'edit'
	    end
	end

	def edit
		@photo =Photo.find(params[:id])
	end

	def create
		@photo = Photo.create(photo_params)

		if @photo.save
			array = @photo.caption.split(' ')
			array.each do |word|
				if word.include?("#")
					@hashtag = Hashtag.create(text: word)
					@photo.hashtags << @hashtag
					@photo.save
				end
			end
			redirect_to photo_path(@photo)
		else
			render :new
		end

	end

	def destroy
    	@photo = Photo.find(params[:id])
    	@photo.destroy
 
    	redirect_to photos_path
   	end

	def show
		@photo=Photo.find(params[:id])
	end

	def index
		@photos = Photo.all
	end

	private

	# Use strong_parameters for attribute whitelisting
	# Be sure to update your create() and update() controller methods.

	def photo_params
	  params.require(:photo).permit(:image, :caption, :hashtag)
	end
end

apps/brugram/app/helpers/application_helper.rb
module ApplicationHelper
end

apps/brugram/app/helpers/hashtags_helper.rb
module HashtagsHelper
end

apps/brugram/app/helpers/photos_helper.rb
module PhotosHelper
end

apps/brugram/app/views/hashtags/index.html.erb
<container>Here's a list of our hashtags!</container>
<p>Click on one to see all the photos with that hashtag or click <%= link_to 'here', photos_path %> to go back to the Full Library</p>
<% @hashtags.each do |tag| %>
	<%=link_to tag.text, hashtag_path(tag)%><br>
<%end%>

apps/brugram/app/views/hashtags/show.html.erb
<div align='center'><br><br><%@hashtag.photos.each do |pic|%>
	<container><%= pic.caption %></container><br><br>
	<%=image_tag pic.image.url(:thumb)%><br><br><br>
<%end%>

<br><%= link_to 'Go to All Hashtags', hashtags_path %><br>
<%= link_to 'Go to the Full Library', photos_path %></div>

apps/brugram/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Brugram</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>